### ISSUE TITLE
CORS 및 필터 예외처리 에러 수정

### ISSUE THREAD

**Issue by Jsim6342** [tell-me-team/Back-End#28]
## Description
---
CORS 및 필터 예외처리 에러 수정

## Todo
---
- [x] 필터 예외처리 에러 수정
- [x] Token 및 UserDetail 구분자 id 값으로 변경
- [x] CORS 설정 수정

## ETC
---
기타사항
