### ISSUE TITLE
설문 이슈

### ISSUE THREAD

**Issue by youngyoung0** [tell-me-team/Back-End#49]
## Description
---
설문 작성이후에 shroturl이 header값이 있는 사람에게 발급되는 부분 수정 및 설문결과 API 익명으로 접근 하도록 수정

## Todo
---
- [x] 설문 작성이후 작성자만 shorturl 발급
- [x] /v1/users/survey-results/{userId}/{surveyId} API 익명도 접근 가능 
- [x] 설문 답변 중복 요청 가능하게 수정
- [x] 설문 결과 유형값 추가
- [x] 익명 유저 response에 다른 사람 키워드 추가
- [x] 상대방 타입 결과 도출 로직 수정(전체 value값 카운트로)
- [x] survey 결과 answerToOther 로직 수정(index 카운트)
- [x] user info response에 survey complete data 추가

## ETC
---
기타사항
