### ISSUE TITLE
spring 활용 test code 작성

### ISSUE THREAD

**Issue by Jsim6342** [tell-me-team/Back-End#56]
## Description
---
spring 의존성을 활용한 test code 작성

## Todo
---
태영 작업 리스트
- [x] 설문 답변 API 테스트 코드 작성
- [x] 설문 링크 URL 디코드 API 테스트 코드 작성
- [x] 설문 질문 리스트 API 테스트 코드 작성

수범 작업 리스트
- [x] 유저 정보 API 테스트 코드 작성
- [x] 설문 결과 API 테스트 코드 작성 
- [x] 소셜 로그인 API 테스트 코드 작성

## ETC
---
spring 의존성을 활용한 test code 작성 후 리팩토링 진행

**Comment by Jsim6342** [comment]
전체 테스트 코드도 실행될 수 있도록 sql 파일 및 설정 등을 조정했습니다.

**Comment by Jsim6342** [comment]
test properties에 jwt secret key 환경변수 설정으로 JwtTokenProvider MockBean 제거했습니다.
